- name: firewall is disabled and stop
  service: name=firewalld state=stopped enabled=no
  tags: iptables

- name: install the latest version of iptables-service
  yum: name=iptables-services state=latest
  tags: iptables

- name: iptables is enabled and started
  service: name=iptables state=running enabled=yes
  tags: iptables

- name: open port 80
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    action: insert
    rule_num: 4
  tags: iptables

- name: open port 443
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    action: insert
    rule_num: 4
  tags: iptables

- name: Set the policy for the INPUT chain to DROP
  iptables:
    chain: INPUT
    policy: DROP
  tags: iptables

- name: Set the policy for the FORWARD chain to DROP
  iptables:
    chain: FORWARD
    policy: DROP
  tags: iptables

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  tags: iptables

- name: restart iptables
  systemd: name=iptables state=restarted 
  tags: iptables
