- name: firewall is disabled and stop
  service: name=firewalld state=stopped enabled=no
  tags: iptables

- name: install the latest version of iptables-service
  yum: name=iptables-services state=latest
  tags: iptables

- name: iptables is enabled and started
  service: name=iptables state=running enabled=yes
  tags: iptables

- iptables_raw:
    name: allow_tcp_80
    rules: '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
  tags: iptables

- name: restart iptables
  systemd: name=iptables state=restarted 
