- name: firewall is disabled and stop
  service: name=firewalld state=stopped enabled=no
  tags: iptables

- name: install the latest version of iptables-service
  yum: name=iptables-services state=latest
  tags: iptables

- name: iptables is enabled and started
  service: name=iptables state=running enabled=yes
  tags: iptables

- name: restart iptables
  systemd: name=iptables state=restarted 
