- name: firewall is disabled and stop
  service: name=firewalld state=stopped enabled=no
  tags: iptables

- name: install the latest version of iptables-service
  yum: name=iptables-services state=latest
  tags: iptables

- name: iptables is enabled and started
  service: name=iptables state=running enabled=yes
  tags: iptables

- name: open port 80
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

    #- name: restart iptables
    #  systemd: name=iptables state=restarted 
